version: '3.8'

services:
  db:
    container_name: postgresdatabase
    image: postgres
    restart: always
    environment:
      POSTGRES_USER : admin
      POSTGRES_PASSWORD : root
      POSTGRES_DB : organizadorDevelopment
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8'
    ports:
      - "5432:5432"


  pgadmin:
    container_name: pgadmin4container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"